ARG BASE_IMAGE=alpine:3.12

FROM ${BASE_IMAGE}
RUN set -xue; \
      apk update && apk add --no-cache \
        apache2-utils \
        bash \
        bind-tools \
        bird \
        bridge-utils \
        busybox-extras \
        conntrack-tools \
        curl \
        dhcping \
        drill \
        ethtool \
        file\
        fping \
        httpie \
        iftop \
        iperf \
        iproute2 \
        ipset \
        iptables \
        iptraf-ng \
        iputils \
        ipvsadm \
        jq \
        libc6-compat \
        liboping \
        mtr \
        net-snmp-tools \
        netcat-openbsd \
        nftables \
        ngrep \
        nmap \
        nmap-nping \
        openssl \
        py-crypto \
        py2-virtualenv \
        scapy \
        socat \
        strace \
        tcpdump \
        tcptraceroute \
        tshark \
        util-linux \
        vim 
