---
- hosts: localhost
  tasks:
    - name: Install packages
      community.general.homebrew:
        name: "{{ item }}"
        state: present
        update_homebrew: yes
      with_items: "{{ os_init.packages }}""
